-- Group project - Online store database --
-- CSCI 466 --
-- Abraham Gonzalez z2012791 --
-- Om Patel z2043569 --
-- Anthony Aguilar-Herrera z1878942 --
-- Jason Rosas z2045088 --

-- Creating tables --

-- USER/ACCOUNT table--
CREATE TABLE USERS
(
    USERID CHAR(10) NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(30) UNIQUE,
    PASSWORD VARCHAR(20) NOT NULL,
    ADDRESS CHAR(40) NOT NULL,
    PHONENUM VARCHAR(15) NOT NULL,
    BILLINFO VARCHAR(25) -- placeholder for encrypted billing token
);

-- PRODUCT table --
CREATE TABLE PRODUCT
(
    PRODUCTID CHAR(2) PRIMARY KEY,
    PNAME VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(20),
    PRICE DECIMAL(10,2) NOT NULL,
    STOCKQTY INT(3) NOT NULL DEFAULT 0
);

-- SHOPPING CART table --
CREATE TABLE SHOPPING_CART
(
    USERID CHAR(10) NOT NULL,
    PRODUCTID CHAR(2) NOT NULL,
    RANDID CHAR(5) NOT NULL,
    ORDERCHECK ENUM('FALSE', 'TRUE') DEFAULT 'FALSE',
    ORDERID CHAR(2),
    USERQTY INT NOT NULL DEFAULT 1,
    PRIMARY KEY (USERID, PRODUCTID, RANDID, ORDERCHECK),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID)
);
-- ORDER table --
-- STATUS should be limited to words of PENDING PROCESSING CANCELLED and COMPLETED --
CREATE TABLE ORDERS
(
    ORDERDATE DATE NOT NULL,
    ORDERID CHAR(2) NOT NULL,
    USERID CHAR(10) NOT NULL,
    TOTAL DECIMAL(10,2) NOT NULL,
    OSTATUS ENUM('PENDING', 'PROCESSING', 'SHIPPED', 'COMPLETED', 'CANCELLED', 'RETURNED') DEFAULT 'PENDING',
    PRIMARY KEY (ORDERID, USERID, ORDERDATE),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

-- SHIPMENT table --
CREATE TABLE SHIPMENT
(
    SHIPDATE DATE NOT NULL,
    SHIPID CHAR(2) PRIMARY KEY,
    ORDERID CHAR(2) NOT NULL,
    TRACKNUM VARCHAR(20) NOT NULL,
    FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID)
);
